def load_state(bucket: str) -> dict:
    ...

def save_state(bucket: str, state: dict) -> None:
    ...

def get_last_successful_run(state: dict) -> str | None:
    ...

def update_event_checkpoint(state: dict, media_id: str, end_date: str) -> dict:
    ...